services:
  - type: web
    name: library-management-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
